// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiRepracionCelular.Entidades;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public string Password { get; set; }

    public int? IdRol { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual ICollection<Reparacion> Reparacion { get; set; } = new List<Reparacion>();
}